<a href="https://colab.research.google.com/github/AIJuand/AI/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Taller II de numpy**

#¿Por qué usar arrays de numpy y no listas o tuplas de python?
Aunque python base tiene listas, el usar arrays es más rápido y consume menos memoria. Algo altamente necesario cuando se hacen operaciones de gran tamaño como puede ser el algebra matricial, por ejemplo.

In [ ]:
import numpy as np

#Creación básica de arrays
Vamos a crear arrays de distintas dimensiones. Para esto podemos usar números, listas o tuplas.

In [ ]:
#Utilizar np. para decir que es una funcion de la librería pandas
a=np.array(13) #array de dimensión 0
b=np.array([1,2,3,4]) #array de dimensión 1
c=np.array([[1,2,3,4],[5,6,7,8]]) #array de dimensión 2
d=np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]]) #array de dimensión 3
#Print se utiliza para imprimir resultados
print("a =",a,"\n")
print("b =",b,"\n")
print("c =",c,"\n")
print("d =",d,"\n")

a = 13 

b = [1 2 3 4] 

c = [[1 2 3 4]
 [5 6 7 8]] 

d = [[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]] 



In [ ]:
#Para revisar el número de dimensiones, usamos ndim
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


#Indexación básica
El proceso de indexación en numpy es similar al de las listas en python. Cada número implica buscar la posición en cada dimensión del array

In [ ]:
print("a =",a)
print("b[2] = ",b[2])
print("c[1] =",c[1])
print("d[1] =",d[1])

a = 13
b[2] =  3
c[1] = [5 6 7 8]
d[1] = [[ 9 10 11 12]
 [13 14 15 16]]


Similarmente podemos segmentar arrays como en el las listas de python

In [ ]:
print(b[2:4]) #b = [1 2 3 4] -> [3 4]
print(c[1,1:3]) #c = [[1 2 3 4][5 6 7 8]] -> [6 7]

[3 4]
[6 7]


#Diferentes tipos de datos en los arrays
Los arrays no están limitados a números enteros, pueden también tener cadenas, booleanos, o de punto flotante.



In [ ]:
frutas = np.array(['Manzana', 'Naranja', 'Uva']) #cadenas
print(frutas.dtype)


<U7


Podemos manipular el tipo de los datos del array dentro de la función de creación del array np.array, siempre y cuando el cambio sea posible. Por ejemplo podemos pasar enteros a cadenas (integers a strings) pero no viceversa.

In [ ]:
number_to_string=np.array([6,1,2,4,623,8], dtype='S') #b denota un string
print(number_to_string.dtype)
print(number_to_string)

|S3
[b'6' b'1' b'2' b'4' b'623' b'8']


In [ ]:
try:
    error_array = np.array(['a', '2', '3'], dtype='i')
except:
    print("hay un error en su lógica")

hay un error en su lógica


Podemos también cambiar el tipo en arrays ya existentes

In [ ]:
floating_array = np.array([1.1, 2.1, 3.1]) #punto flotante

int_array = floating_array.astype('i')
print(int_array)
print(floating_array)

[1 2 3]
[1.1 2.1 3.1]


#Forma de los arrays
La forma es distinta a la dimensión. Esta se define como el número de elementos de la dimensión.

In [ ]:
print(a.shape) # a = 13 
print(b.shape) # b = [1 2 3 4] 
print(c.shape) # c = [[1 2 3 4][5 6 7 8]] 
print(d.shape) # d = [[[ 1  2  3  4][ 5  6  7  8]] [[ 9 10 11 12][13 14 15 16]]] 

()
(4,)
(2, 4)
(2, 2, 4)


#Reformar arrays
Podemos cambiar la forma de los arrays. Esto significa aumentar el número de dimensiones o cambiar cuantos elementos hay por dimensión.

In [ ]:
print("c =",c,"\n")
c_1D=c.reshape(1,8)
print("c_1D =",c_1D,"\n")
c_4D=c.reshape(4,2)
print("c_4D =",c_4D,"\n")

c = [[1 2 3 4]
 [5 6 7 8]] 

c_1D = [[1 2 3 4 5 6 7 8]] 

c_4D = [[1 2]
 [3 4]
 [5 6]
 [7 8]] 



¿Podemos hacer cualquier cambio en la forma? Si, mientras las que se quieren conseguir coincidan con la cantidad de elementos.

In [ ]:
print(d)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


In [ ]:
d.reshape(2,2,2,2)

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]]])


#Dimensión desconocida
Podemos definir el cambio de forma con una dimensión la cual no sabemos el tamaño. Numpy se encargará de definir el tamaño que mejor se ajuste.

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr.reshape(3,-1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Podemos usar la dimensión desconocida para "aplanar" el array a una dimensión.

In [ ]:
d.reshape(-1)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

#Transpuesta
Para transponer el array utilizamos .T

In [ ]:
print("c =",c,"\n")
print("c.T =",c.T)

c = [[1 2 3 4]
 [5 6 7 8]] 

c.T = [[1 5]
 [2 6]
 [3 7]
 [4 8]]


#Iterar arrays
Podemos usar los métodos tradicionales para iterar.

In [ ]:

for x in d:
    print(x)

[[1 2 3 4]
 [5 6 7 8]]
[[ 9 10 11 12]
 [13 14 15 16]]


Si queremos iterar cada elemento, necesitamos un for por cada dimensión

In [ ]:
for x in d:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16


*OPTIMO*

Esto por supuesto no es óptimo. Así que numpy tiene la función nditer() para estos casos.

In [ ]:
for x in np.nditer(d):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16


#Aplicar operaciones entre arrays
numpy tiene sus propias formas de aplicar operaciones:

#Suma
numpy tiene dos funciones, np.add() y np.sum(). El primero se aplica entre argumentos, el segundo se aplica en n elementos para que se haga la suma, es necesario que ambos arrays tengan la misma forma

In [ ]:
arr1=np.array([[1,2,3],
               [4,5,6]])
arr2=np.array([[6,5,4],
               [3,2,1]])
np.add(arr1,arr2)

array([[7, 7, 7],
       [7, 7, 7]])

In [ ]:
arr3=np.array([[1,1,1],[1,1,1]])
print(np.sum([arr1,arr2]))
print(np.sum([arr1,arr2,arr3]))

42
48


Si aplicamos un eje en np.sum(), se aplica la suma en ese mismo eje. Por ejemplo, con eje 0, se obtienen los mismos resultados que np.add()

In [ ]:
np.sum([arr1,arr2, arr3],axis=0)

array([[8, 8, 8],
       [8, 8, 8]])

In [ ]:
np.sum([arr1,arr2, arr3],axis=1)

array([[5, 7, 9],
       [9, 7, 5],
       [2, 2, 2]])

#Multiplicación
El primer caso de multiplicación es np.prod(), que funciona similar que np.sum()

In [ ]:
print("arr1=\n",arr1,"\n")
print("arr2=\n",arr2,"\n")
print(np.prod([arr1,arr2]),"\n")
print(np.prod([arr1,arr2],axis=0),"\n")
print(np.prod([arr1,arr2],axis=1))#con uno es cruzado

arr1=
 [[1 2 3]
 [4 5 6]] 

arr2=
 [[6 5 4]
 [3 2 1]] 

518400 

[[ 6 10 12]
 [12 10  6]] 

[[ 4 10 18]
 [18 10  4]]


#Multiplicación Matricial
Para la multiplicación de matrices usamos np.matmul() o np.dot(). hay que tener en cuenta la forma de las matrices

In [ ]:
np.matmul(arr1, arr2.T)

array([[28, 10],
       [73, 28]])

In [ ]:
np.dot(arr1, arr2.T)

array([[28, 10],
       [73, 28]])

Se comportan distinto con matrices de dos dimensiones, para otros casos hacen cosas distintas

In [ ]:
print("d =\n",d,"\n") #2,2,4
print("d.reshape =\n",d.reshape(2,4,2),"\n") #2,4,2
np.dot(d,d.reshape(2,4,2)) #2,2,2,2

d =
 [[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]] 

d.reshape =
 [[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]] 



array([[[[ 50,  60],
         [130, 140]],

        [[114, 140],
         [322, 348]]],


       [[[178, 220],
         [514, 556]],

        [[242, 300],
         [706, 764]]]])

In [ ]:
#particion del anterior resultado
print(np.dot(d[0],d.reshape(2,4,2)[0]),"\n")
print(np.dot(d[0],d.reshape(2,4,2)[1]),"\n")
print(np.dot(d[1],d.reshape(2,4,2)[0]),"\n")
print(np.dot(d[1],d.reshape(2,4,2)[1]),"\n")

[[ 50  60]
 [114 140]] 

[[130 140]
 [322 348]] 

[[178 220]
 [242 300]] 

[[514 556]
 [706 764]] 



Con matmul no se pueden multiplicar escalares c.A (c escalar, A matriz), además Matmul hace las multiplicaciones matriz a matriz (matrices como elementos), de ahí la diferencia con dot, donde este toma los números dentro de las matrices como elementos.

In [ ]:
np.matmul(d,d.reshape(2,4,2))

array([[[ 50,  60],
        [114, 140]],

       [[514, 556],
        [706, 764]]])

Con la información vista en Computación estadistica se enrequisará el tema de numpy

#Creación y modificación de variables
Operadores aritméticos, lógicos, y de comparación

In [ ]:
import pandas as pd

In [ ]:
Municipios = pd.read_excel("Municipios.xlsx",dtype={"Irural":np.float64,"Dep":str,
                                                    "Poblacion":np.float64,"Depmun":str})

Cuales variables del conjunto de datos Municipios tienen valores perdidos o missings?

In [ ]:
def missings(x):
            a = sum(x.isna())
            b = 100*np.mean(x.isna()) # np.mean hace un promedio
            c = pd.Series({"Missings": a,"%Missings": b})
            return(c)

Cálculo de algunas estadísticas descriptivas (personalizadas) para las variables numéricas en el conjunto de datos Municipios.

In [ ]:
def summary(y,include='numeric'):
    def numer(x):
        x2 = x.dropna()
        h = np.quantile(x2,0.25)
        i = x2.median()
        j = np.quantile(x2,0.75)
        l = pd.Series({"%25":h,"Median":i,"%75":j,"Max":k})
        return(l)

In [ ]:
Traza de una matriz
La traza de una matriz cuadrada se calcula con el siguiente método:
a.trace() : Devuelve la traza (suma de la diagonal principal) de la matriz cuadrada a.

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a.trace())

15


Determinante de una matriz
El determinante de una matriz cuadrada se calcula con la siguiente función:

det(a) : Devuelve el determinante de la matriz cuadrada a.

In [ ]:
a = np.array([[1, 2], [3, 4]])
print(np.linalg.det(a))

-2.0000000000000004


Matriz inversa
La inversa de una matriz se calcula con la siguiente función:

inv(a) : Devuelve la matriz inversa de la matriz cuadrada a.

In [ ]:
a = np.array([[1, 2], [3, 4]])
print(np.linalg.inv(a))

[[-2.   1. ]
 [ 1.5 -0.5]]


Autovalores de una matriz
Los autovalores de una matriz cuadrada se calculan con la siguiente función:

eigvals(a) : Devuelve los autovalores de la matriz cuadrada a.

In [ ]:
 a = np.array([[1, 1, 0], [1, 2, 1], [0, 1, 1]])
print(np.linalg.eigvals(a))

[ 3.00000000e+00  1.00000000e+00 -3.36770206e-17]


Autovectores de una matriz
Los autovectores de una matriz cuadrada se calculan con la siguiente función:

eig(a) : Devuelve los autovalores y los autovectores asociados de la matriz cuadrada a.

In [ ]:
a = np.array([[1, 1, 0], [1, 2, 1], [0, 1, 1]])
print(np.linalg.eig(a))

(array([ 3.00000000e+00,  1.00000000e+00, -3.36770206e-17]), array([[-4.08248290e-01,  7.07106781e-01,  5.77350269e-01],
       [-8.16496581e-01,  2.61239546e-16, -5.77350269e-01],
       [-4.08248290e-01, -7.07106781e-01,  5.77350269e-01]]))


Solución de un sistema de ecuaciones
Para resolver un sistema de ecuaciones lineales se utiliza la función siguiente:

solve(a, b) : Devuelve la solución del sistema de ecuaciones lineales con los coeficientes de la matriz a y los términos independientes de la matriz b.

In [ ]:
# Sistema de dos ecuaciones y dos incógnitas
# x + 2y = 1
# 3x + 5y = 2 
a = np.array([[1, 2], [3, 5]])
b = np.array([1, 2])
print(np.linalg.solve(a, b))

[-1.  1.]


Otras operaciones aritmeticas

In [ ]:
arr = np.arange(4)

arr

array([0, 1, 2, 3])

In [ ]:
np.sqrt(arr) #Puedes calcular la raíz cuadrada de cada elemento


array([0.        , 1.        , 1.41421356, 1.73205081])

In [ ]:
np.exp(arr) #Devuelve e ^ elemento para cada elemento del arreglo



array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692])

In [ ]:
np.sin(arr) #Calcula el seno trigonométrico de cada valor en el arreglo


array([0.        , 0.84147098, 0.90929743, 0.14112001])

In [ ]:

np.cos(arr) #Calcula el coseno trigonométrico de cada valor en el arreglo



array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 ])

In [ ]:
np.log(arr) #Calcula el logaritmo en base diez de cada valor en el arreglo

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229])

In [ ]:
arr = np.random.rand(5) #aleatorios
arr

array([0.49151775, 0.26985919, 0.542855  , 0.27551044, 0.75950114])

redondear cada elemento a 2 decimales usando el método round de NumPy:

In [ ]:
arr = np.round(arr, 2)
arr

array([0.17, 0.8 , 0.99, 0.14, 0.54])